### ISSUE TITLE
ZE14-O3 is not working

### ISSUE THREAD

**Issue by Obaid91** [lukas-kurka/winsen-sensors-lib#1]
Hello,

I hope you are well. I am a new learner of the Arduino system. Sorry if my questions are silly. I am getting the error: -4.0 ppm O3 which I guess is "no message in buffer".

I am using Arduino UNO R3. I was able to upload the library of ZE14-O3. I copied the program (example:hardwareserial), changed baud to  9600 as mentioned in the code and datasheet of ZE14-O3. and then upload it. When I run the program,  
RX led is not blinking whereas TX led is blinking. I think the sensor is not sending any data to Arduino. 
I connected to V to 5V, GND to GND, TX to RX and RX to TX. 

Please can you tell me what I am doing wrong? 

Thank you

**Comment by lukas-kurka** [comment]
Hi, from what you have written I suspect that you don’t have your wiring correct.

Arduino UNO has only one hardware UART and you are trying to use it for two different communication channels _ZE14-O3 <—> UNO_ and _UNO <—> computer_. That won’t work, at least easily..

Try to connect your ZE14-O3 to pins 2 and 3 on your UNO and use ze14-softwareserial example instead (just change the pins in there respectively). No need to change the baudrate from 115200 as that is the speed UNO communicates with your computer. Those 9600 is speed which is used between sensor and UNO and you don’t have to care about that, library does.

Other option would be to use other board with more than one hardware UART e.g. Mega 2560, ESP32..

**Comment by Obaid91** [comment]
Thank you for your response. 

I connected the sensor (RX) to 3, and the sensor (TX) to 2. Now the sensor is showing 0.0 ppm. Do you think this is working? Still, the RX led on Arduino is not blinking, not TX led is blinking. 

Thank you



> Hi, from what you have written I suspect that you don’t have your wiring correct.
> 
> Arduino UNO has only one hardware UART and you are trying to use it for two different communication channels _ZE14-O3 <—> UNO_ and _UNO <—> computer_. That won’t work, at least easily..
> 
> Try to connect your ZE14-O3 to pins 2 and 3 on your UNO and use ze14-softwareserial example instead (just change the pins in there respectively). No need to change the baudrate from 115200 as that is the speed UNO communicates with your computer. Those 9600 is speed which is used between sensor and UNO and you don’t have to care about that, library does.
> 
> Other option would be to use other board with more than one hardware UART e.g. Mega 2560, ESP32..

**Comment by lukas-kurka** [comment]
> Now the sensor is showing 0.0 ppm. Do you think this is working?

I dare to say it is. Or at least it is transmitting data as it should. There are several checks for message structure and checksum as well. It is highly improbable that the library would pass you invalid reading which you would consider valid in this case in range 0.0 - 100.0 ppm. 

The sensor is somewhat sensitive to other gases and higher airflow. You can try to blow directly on the sensor with your mouth for several seconds, you should get some tenths for a while before the sensor stabilizes again. Or if you have source of ozone try it with that but be careful not to expose yourself to high concentration.

Some things to consider
 - the resolution of sensor is 0.1ppm which under normal circumstances is not what you would measure in ambient air (if you would go for ZE25-O3 that has resolution of 0.01ppm and that would usually give you some thousandths)
 - the sensor should be powered for at least 5 hours before first use

> Still, the RX led on Arduino is not blinking, not TX led is blinking.

I’m not completely sure about the RX / TX leds.. Anyway I would say that the RX led has no reason to blink, you are not sending anything from your computer to UNO when running this example code. The TX led might be blinking but the message send to serial is pretty short so it might be that it blinks for so short that you don’t register it. But so far that is only my guess.

**Comment by Obaid91** [comment]
Thank you for your response.I blew the air and it shows 1.6 ppm for few seconds. Now I will try to add LED screen to the Arduino. Can I use two arduino on computer at a same time? 

Thank you

> I dare to say it is. Or at least it is transmitting data as it should. There are severa
> The sensor is somewhat sensitive to other gases and higher airflow. You can try to blow directly on the sensor with your mouth for several seconds, you should get some tenths for a while before the sensor stabilizes again. Or if you have source of ozone try it with that but be careful not to expose yourself to high concentration.
> 
> Some things to consider
> 
> * the resolution of sensor is 0.1ppm which under normal circumstances is not what you would measure in ambient air (if you would go for ZE25-O3 that has resolution of 0.01ppm and that would usually give you some thousandths)
> * the sensor should be powered for at least 5 hours before first use
> 
> > Still, the RX led on Arduino is not blinking, not TX led is blinking.
> 
> I’m not completely sure about the RX / TX leds.. Anyway I would say that the RX led has no reason to blink, you are not sending anything from your computer to UNO when running this example code. The TX led might be blinking but the message send to serial is pretty short so it might be that it blinks for so short that you don’t register it. But so far that is only my guess.

**Comment by lukas-kurka** [comment]
> Can I use two arduino on computer at a same time?

This isn’t related to this library and it is quite a basic question, you should read some documentation.
