### ISSUE TITLE
example.yaml file for ESPHome for WeMos D1 mini or ESP32-C3. 

### ISSUE THREAD

**Issue by BatrakovSV** [lukas-kurka/winsen-sensors-lib#2]
Hello. I'm completely new.
Could you create an example.yaml file for ESPHome?
Here's how it's done here.
https://gist.github.com/cretep/f96606dc6a4eae0d85993d6085959220

**Comment by lukas-kurka** [comment]
Hi, adding libraries to ESPHome takes more than just a code for sensors. You need to know how the implementation is done and follow some guidelines. I definitely don’t have time to study and comply with those at this moment.

**Comment by BatrakovSV** [comment]
Could I use library (winsen_ze08.h) for ZE25?
![Снимок экрана 2024-02-05 в 12 21 53](https://github.com/lukas-kurka/winsen-sensors-lib/assets/42162732/b3027fbf-7e96-4d51-9a83-863d9dde45ed)

**Comment by lukas-kurka** [comment]
Those are just instructions for setting operating modes of those sensors, decoding of sensor messages is something different. You have to check datasheets of both.

**Comment by BatrakovSV** [comment]
Can I use your h and cpp files for this? Will this work? It's enough?
https://esphome.io/components/external_components#

**Comment by lukas-kurka** [comment]
It doesn’t have the requried structure, so it won’t work.
