### ISSUE TITLE
Custom UART Device from ZE08 to ZE25

### ISSUE THREAD

**Issue by BatrakovSV** [lukas-kurka/winsen-sensors-lib#3]
I compared the datasheets on the ZE08 and ZE25.
And we came to the conclusion that they are similar.
Therefore, I believe that you can use this code https://gist.github.com/cretep/f96606dc6a4eae0d85993d6085959220
for this technology
https://esphome.io/custom/uart.html
Your opinion?

**Comment by lukas-kurka** [comment]
If you think it can be done then go ahead and adapt the code for the use you need:-) That's actually why it is published on GitHub and under GPL. Code implementation to ESPHome is not currently my point of interest nor I have enough time to guide you through this process.

**Comment by BatrakovSV** [comment]
Can you leave this issue open for now?
I'll probably buy a ZE25-O3 and write here if I was able to implement it.


![Снимок экрана 2024-02-07 в 23 15 06](https://github.com/lukas-kurka/winsen-sensors-lib/assets/42162732/954c501b-10e0-4b7f-8ec7-953be3ffa70f)

**Comment by lukas-kurka** [comment]
I understand your point however this is not issue of this library. It much more concerns implementation to ESPHome, so it should be discussed [there](https://github.com/esphome/esphome/issues) or even if you have working code that follows guidelines you can create [pull request](https://github.com/esphome/esphome/pulls) so it is incorporated and others can enjoy it as well.
